
worker_process 1;

event {
  worker_connections 1024;
}

http {
  upstream server_cluster {
    # Load balancing algorithm
    # The default strategies is round robin
    least_conn;

    # All the server that the nginx can forward request
    server 127.0.0:8080;
    server 127.0.0:8081;
    server 127.0.0:8082;
  }


  server {
    listen 443 ssl;
    server name localhost;

    ssl_certificate /path_to_the_cert;
    ssl_certificate /path_to_private_key;

    location / {
      proxy_pass http://server_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real_IP $remote_addr;
    }
  }

  server {
    listen 80;
    server_name localhost;

    location / {
      return 301 https://$host$request_uri; # Return to https request
    }
  }
}