export enum QuestionType {
  MULTIPLE_CHOICE,
  SHORT_ANSWER,
  MULTIPLE_QUESTIONS,
  DROPDOWN_ANSWER,
  LABEL_ON_MAP,
  FILL_IN_THE_GAP,
  MATCHING_HEADER,
  DRAG_AND_DROP_ANSWER,
  FILL_IN_THE_TABLE,
  DRAG_IN_TABLE
}
